services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: timebeing
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql+psycopg://postgres:postgres@db:5432/timebeing
      OTEL_SERVICE_NAME: TimeBeingBackEnd
      OTEL_EXPORTER_OTLP_ENDPOINT: otel:4317
      OTEL_EXPORTER_OTLP_INSECURE: true
      OTEL_PYTHON_LOGGING_AUTO_INSTRUMENTATION_ENABLED: true
      OTEL_TRACES_EXPORTER: otlp
      OTEL_METRICS_EXPORTER: otlp
      OTEL_LOGS_EXPORTER: otlp
    volumes:
      - ./timebeing_backend:/app/timebeing_backend
      - ./alembic:/app/alembic
      - ./alembic.ini:/app/alembic.ini
    command: >
      sh -c "
        poetry run alembic upgrade head &&
        poetry run opentelemetry-instrument uvicorn --host 0.0.0.0 --port 8000 timebeing_backend.main:app 
      "

  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@timebeing.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "5050:80"
    depends_on:
      - db
    volumes:
      - pgadmin_data:/var/lib/pgadmin

  otel:
    image: grafana/otel-lgtm
    ports:
      - "3001:3000"
      - "4317:4317"

volumes:
  postgres_data:
  pgadmin_data:
