"""altering habit table for nullable columns 

Revision ID: 168f31341020
Revises: 4c2892d58714
Create Date: 2025-06-25 11:56:09.510485

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '168f31341020'
down_revision: Union[str, Sequence[str], None] = '4c2892d58714'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('habit', 'description',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('habit', 'current_score',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('habit', 'ai_context_prompt',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('habit', 'ai_context_prompt',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('habit', 'current_score',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('habit', 'description',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
