"""altering task for nullable columns 

Revision ID: 4c2892d58714
Revises: 8b419018afc2
Create Date: 2025-06-25 11:12:39.512161

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c2892d58714'
down_revision: Union[str, Sequence[str], None] = '8b419018afc2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('task', 'project_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('task', 'project_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
