"""Add scheduled time on tasks

Revision ID: 580f115b7a5a
Revises: adccf34a9834
Create Date: 2025-07-01 13:55:16.458492

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '580f115b7a5a'
down_revision: Union[str, Sequence[str], None] = 'adccf34a9834'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('scheduled_start_time', sa.DateTime(), nullable=True))
    op.add_column('task', sa.Column('scheduled_end_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'scheduled_end_time')
    op.drop_column('task', 'scheduled_start_time')
    # ### end Alembic commands ###
