"""habit default prompt = "" 

Revision ID: 66c7ef3f6e4e
Revises: 8ec1fb8281a7
Create Date: 2025-06-23 22:01:54.947862

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '66c7ef3f6e4e'
down_revision: Union[str, Sequence[str], None] = '8ec1fb8281a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
