"""creating tables relationships 

Revision ID: 8b419018afc2
Revises: 9687da379a54
Create Date: 2025-06-25 10:46:42.272051

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b419018afc2'
down_revision: Union[str, Sequence[str], None] = '9687da379a54'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('parent_task_id', sa.UUID(), nullable=True))
    op.add_column('task', sa.Column('project_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'task', 'task', ['parent_task_id'], ['id'])
    op.create_foreign_key(None, 'task', 'project', ['project_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'task', type_='foreignkey')
    op.drop_constraint(None, 'task', type_='foreignkey')
    op.drop_column('task', 'project_id')
    op.drop_column('task', 'parent_task_id')
    # ### end Alembic commands ###
