"""creating task table 

Revision ID: a91c03948027
Revises: 66c7ef3f6e4e
Create Date: 2025-06-24 19:05:34.079772

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a91c03948027'
down_revision: Union[str, Sequence[str], None] = '66c7ef3f6e4e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task',
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('due_date', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('aberta', 'andamento', 'concluida', name='statusstate'), nullable=False),
    sa.Column('priority', sa.Enum('baixa', 'media', 'alta', name='prioritystate'), nullable=False),
    sa.Column('duration_estimate_blocks', sa.Integer(), nullable=True),
    sa.Column('location_text', sa.String(), nullable=True),
    sa.Column('location_lat', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('location_lon', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('ai_context_text', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('task')
    # ### end Alembic commands ###
