"""atualizando tabela tasks para ter notify_date

Revision ID: e1de12db14d6
Revises: 2656ac15afd5
Create Date: 2025-07-31 19:47:11.955880

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e1de12db14d6'
down_revision: Union[str, Sequence[str], None] = '2656ac15afd5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('notify_at', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'notify_at')
    # ### end Alembic commands ###
